glusterfs-server:
  image: quay.io/webcenter/rancher-glusterfs-server:test
  cap_add:
    - SYS_ADMIN
  volumes_from:
    - glusterfs-data
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: glusterfs-manager,glusterfs-data
  command: "glusterd -p /var/run/gluster.pid -N"
glusterfs-manager:
  image: quay.io/webcenter/rancher-glusterfs-server:test
  net: 'container:glusterfs-server'
  volumes_from:
    - glusterfs-data
  labels:
    io.rancher.container.hostname_override: container_name
  command: /app/init.py
glusterfs-data:
  image: quay.io/webcenter/rancher-glusterfs-server:test
  command: /bin/true
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
