glusterfs-server:
  image: quay.io/webcenter/rancher-glusterfs-server:test
  cap_add:
    - SYS_ADMIN
  volumes_from:
    - glusterfs-data
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: glusterfs-data
  command: /app/run
  tty: true
  stdin_open: true
glusterfs-data:
  image: quay.io/webcenter/rancher-glusterfs-server:test
  command: /bin/true
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
